---
# Source: ada-stake-pool/templates/deployment-bpnode.yaml
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  labels:
    app: RELEASE-NAME-ada-stake-pool
    chart: "ada-stake-pool-0.0.1-pre1"
    heritage: "Helm"
    release: "RELEASE-NAME"
  name: bpnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RELEASE-NAME-ada-stake-pool
      release: "RELEASE-NAME"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
  template:
    metadata:
      annotations:
        ## Only scrape pods that have a value of `true`
        prometheus.io/scrape: "true"
        ## If the metrics path is not `/metrics` override this.
        prometheus.io/port: "9102"
        ## scrape the pod on the indicated port instead of the default of `9102`.
        prometheus.io/path: "metrics"
        ## Scrape the pod over protocol
        prometheus.io/scheme: "http"
        ##
        ## Oftentimes, applicatins need to be restarted once once their configuration has been updated. However,
        ## Kubernetes makes the assumption that watching the file for configuration change is the applications
        ## responsibiliy, and doesn't restart when files change. So, the lines below modify a propery that does trigger
        ## a rotation of the applications so they are restarted when their dependencies change.
        ##
        ## See https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md
        ##   #automatically-roll-deployments-when-configmaps-or-secrets-change
        ##
        # checksum/config: 14e8c727b912418c431dfbfce25426f8e69c22f0086d4ad355c0b553d35f4a78
        # checksum/config: a6d4d171207048a4e861f79da94209f102643790c1eab79f61b126f0e978d027
      labels:
        app: RELEASE-NAME-ada-stake-pool
        release: "RELEASE-NAME"
    spec:
      ## Volumes are how Kubernetes expresses either networked storage or other metadata in the filesystem. There are
      ## storage types, the most useful of which are illustrated below. Remember to uncomment the volumes: node if you
      ## decide to use them!
      ##
      volumes:
      ##
      ## EMPTY DIR - Useful for scratch space, such as for CI
      ##
      #   - name: "__VOLUME_NAME__"
      #     emptyDir: {}
      ##
      ## HOST PATH - Useful when mounting some host proprty into hte container
      ##
      #   - name: "__VOLUME_NAME__"
      #     hostPath:
      #       path: "/path/to/your/folder"
      ##
      ## PERSISTENT VOLUME CLAIM - Useful to access network storage. Should be used in preference to GcePersistantDisk
      ##                           et. al. You will need to define a persistent volume as well, for this to work.
      ##
        - name: "data"
          persistentVolumeClaim:
            claimName: RELEASE-NAME-ada-stake-pool-bpnode
      ##
      ## CONFIGMAP
      ##
      #   - name: "__VOLUME_NAME__"
      #     configMap:
      #       name: "__CONFIGMAP_NAME__"
      ##
      ## Note: You can also use single files from a configmap, with a syntax called "subPath". An example is below:
      ##
      #   - name: "__VOLUME_NAME__"
      #     configMap:
      #       name: "__CONFIGMAP_NAME__"
      #       items:
      #         - key: "__ITEM_KEY__"
      #           path: "path/to/item"
      ##
      ## SECRET
      ##
      #   - name: "__VOLUME_NAME__"
      #     secret:
      #       secretName: "__SECRET_NAME__"
      ##
      ## DOWNWARD API
      ##
      #   - name: "__VOLUME_NAME__"
      #     downwardAPI:
      #       items:
      #         - path: "labels"
      #           fieldRef:
      #             fieldPath: metadata.labels
      #         - path: "annotations"
      #           fieldRef:
      #             fieldPath: metadata.annotations
      containers:
        - name: bpnode
          image: "map[pullPolicy:IfNotPresent registry:docker.io repository:inputoutput/cardano-node tag:1.18.0]"
          env:
            - name: NETWORK
              value: mainnet
          # command: [ "run" ] 
          # args: 
          #   - "--config"
          #   - "/configuration/configuration.yaml"
          #   - "--topology"
          #   - "/configuration/topology.json"
          #   - "--database-path" 
          #   - "/db"
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
          # ports:
          #   - containerPort: 3000
          #     protocol: "TCP"
          #     name: "tcp-3000"
          volumeMounts:
          #   - name: "webserver-etc-conf-d"
          #     readOnly: true
          #     mountPath: "/etc/webserver/conf.d"
            - name: "data"
              readOnly: false
              mountPath: "/data"
          ## There are three types or readiness probes:
          ##
          ## More generally, a liveness probe is used to determine whether the application is "healthy" and should
          ## recieve traffic. Whereas, a readiness probe is used to determine whether the application has finished
          ## its boot and is now online
          ##
          ## - HTTP Liveness
          ## - TCP Liveness
          ## - Exec liveness
          ##
          ## Below are examples of each healthcheck type with descriptions of when to use them
          ##
          # livenessProbe:
            ##
            # tcpSocket:
            ##
            ## The "tcpSocket" health check is useful for when an application exposes a port, but there are no utilities
            ## to determine whether that application is healthy over that port. So, the fact the application is
            ## listening on that port is taken as a "proxy" health measure.
            ##
            ##
              # port: "__CONTAINER_PORT_NAME__"
              ## Number of seconds after the container has started before liveness probes are initiated.
              ## See http://kubernetes.io/docs/user-guide/pod-states#container-probes
              ##
              # initialDelaySeconds: 5
              ##
              ## Number of seconds after which the probe times out. Minimum value is 1
              ##
              # timeoutSeconds: 1
              ##
              ## Minimum consecutive failures for the probe to be considered failed after having succeeded.
              ## Minimum value is 1.
              ##
              # failureThreshold: 3
              ##
            ##
            # exec:
            ##
            ## The "exec" healthcheck is useful when there is a bundled program to determine whether the application is
            ## healthy (such as "mysqladmin ping"). It is also useful if the application does not open a network port
            ## for communicating with other applications, but still represents its state on disk somehow.
            ##
              ## The command executed by exec is expected to return "0" to indicate healthy, and any nonzero status code
              ## to indicate unhealthy.
              # command:
                # - cat
                # - /tmp/healthy
              ##
              # initialDelaySeconds: 5
              ##
              ## Number of seconds after which the probe times out. Minimum value is 1
              ##
              # timeoutSeconds: 1
              ##
              ## Minimum consecutive failures for the probe to be considered failed after having succeeded.
              ## Minimum value is 1.
              ##
              # failureThreshold: 3
            ##
            # httpGet:
            #
            ## As the name implies, the "httpGet" health check places a HTTP GET request to an endpoint defined by the
            ## the application. It seems to be the superior method of health checking where the application supports
            ## HTTP, as the semantics are known and usually reliable.
            ##
              ## The path that the HTTP GET request will be made to. Any code > 200 and < 400 is OK. Any other code is
              ## not OK
              ##
              # path: /healthz
              ##
              ## If the application exposes the health checking port on a non standard port, indicate here. Otherwise,
              ## use a named application port defined above.
              ##
              # port: "__CONTAINER_PORT_NAME__"
              ##
              ## Whether to connect using the "HTTP" or "HTTPS" protocol (i.e. whether to enscapsulate the connection in
              ## TLS.
              ##
              # scheme: "HTTP"
              ##
              ## Additional HTTP headers can be supplied to the HTTP health check to modify the behaviour, such as to
              ## supply a HOST header.
              ##
              # httpHeaders:
                # - name: "X-Custom-Header"
                #   value: "Awesome"
              ##
              ## How long to wait between probes
              ##
              # periodSeconds: 10
              ##
              # initialDelaySeconds: 5
              ##
              ## Number of seconds after which the probe times out. Minimum value is 1
              ##
              # timeoutSeconds: 1
              ##
              ## Minimum consecutive failures for the probe to be considered failed after having succeeded.
              ## Minimum value is 1.
              ##
              # failureThreshold: 3
          ## The Readiness probe follows exactly the same syntax as the liveness probe, and the examples above can
          ## be reused.
          ##
          # readinessProbe:
          ##
          ## __LIVENESS_PROBE__
      ## Whether to restart this pod. Possible values are:
      ## - Always (Sensible Default)
      ## - OnFailure
      ## - Never
      ##
      ## For more information, see http://kubernetes.io/docs/user-guide/pod-states/#restartpolicy
      restartPolicy: "Always"
      securityContext:
        ## Volumes which support ownership management are modified to be owned and writable by the GID specified in
        ## fsGroup. See the Ownership Management design document for more details.
        ## See: https://github.com/kubernetes/community/blob/master/contributors/design-proposals/
        ##      volume-ownership-management.md
        # fsGroup: 1000
        ## A list of groups applied to the first process run in each container, in addition to the containerâ€™s primary
        ## GID. If unspecified, no groups will be added to any container.
        # supplementalGroups: [1000]
